title: "BACKMOJI"
description:  "The Bitmoji Avatar History Enumerator"
#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: fongandrew/hydeout
#remote_theme: samarsault/plainwhite-jekyll/

author: WebBreacher
show_excerpts: false # set to true to show excerpts on the homepage
