title: BACKMOJI
description:  "The Bitmoji Avatar History Enumerator"
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: samarsault/plainwhite-jekyll/

url: "backmoji.osint.ninja" # the base hostname & protocol for your site, e.g. http://example.com
